### ISSUE TITLE
`AttributeError: 'Application' object has no attribute 'parse_preliminary_options'` running tests on macOS

### ISSUE THREAD

**Issue by ncalexan** [mozilla/opmon#127]
```sh
$ pytest --black --flake8 --pydocstyle --ignore=opmon/tests/integration opmon/bigquery_client.py
...
FAILED opmon/bigquery_client.py::flake-8::FLAKE8 - AttributeError: 'Application' object has no attribute 'parse_preliminary_options'
```
I'm on current `main`: `84e49040a3ce5700a356e8fdfebc2a60f8836da5`, with no changes.

@relud suggests that `pytest-flake8` is abandoned.  This ticket tracks cleaning up the repo so that I can run tests again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-716)

**Comment by relud** [comment]
workaround: don't specify `--flake8` when running `--pytest`, e.g.:
```sh
$ flake8 opmon
$ pytest --black --pydocstyle --ignore=opmon/tests/integration opmon/bigquery_client.py
```
