### ISSUE TITLE
Add a DAG for running backfills

### ISSUE THREAD

**Issue by scholtzan** [mozilla/opmon#132]
Currently, backfills need to run through the CLI via `opmon backfill ...`. It would be convenient to offer an Airflow DAG where required parameters can be specified to trigger a backfill. This DAG will likely be similar to the existing [backfill DAG](https://workflow.telemetry.mozilla.org/dags/backfill/grid)

cc @ncalexan

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-737)

**Comment by ncalexan** [comment]
Are backfills incremental, meaning that if I add a new metric (or remove a metric) from some definition TOML file, then `opmon backfill ...` does only the work required for the changed metrics?  As the system grows, this will grow in importance.

**Comment by scholtzan** [comment]
Some additional info why incremental backfills are hard (but would still nice to have for the reasons mentioned): 
* when backfilling the entire table partition needs to be replaced in BigQuery. It would be possible to copy existing data into a temporary table, compute the new metric values, join them to this temporary table and replace the existing partition of the final result table in BigQuery. Deleting metrics would need to be handled differently. Cases where metrics get added, changed, deleted at the same time are even more complicated.
* OpMon needs to store the definition of each metric to determine if it was changed to decide whether to backfill it or not. For each project it needs to store the state of the config it used during the last run (a commit hash would likely be enough here).

**Comment by scholtzan** [comment]
There is some renewed desire for having a DAG set up for this: https://mozilla.slack.com/archives/C4D5ZA91B/p1709923393958799

**Comment by scholtzan** [comment]
https://github.com/mozilla/telemetry-airflow/pull/1946
