### ISSUE TITLE
opsmon dashboard link for new rollout not working

### ISSUE THREAD

**Issue by dmose** [mozilla/opmon#145]
https://experimenter.services.mozilla.com/nimbus/updated-import-infrequent-rollout-make-yourself-at-home-copy/summary was rolled out recently, and has an OpsMon dashboard link (https://mozilla.cloud.looker.com/dashboards/operational_monitoring::updated_import_infrequent_rollout_make_yourself_at_home_copy) which leads to this:

<img width="751" alt="grafik" src="https://user-images.githubusercontent.com/425657/234328390-281778ca-334e-498f-86c6-d8797c3d7f88.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-846)

**Comment by scholtzan** [comment]
The link works for me:

![Screenshot 2023-05-03 at 10 23 42 AM](https://user-images.githubusercontent.com/1239705/235993905-6f35c06a-9a41-4f31-817b-0c0f275ee4c0.png)

There is some delay from when the rollout gets launched to when the dashboard is available. It's usually a day.
Also make sure that you are not in Development Mode in Looker while accessing the dashboard.
